name: CI

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[ci-skip]') }}
    strategy:
      matrix:
        java: [ '17' ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Initialize submodules
        run: |
          git submodule update --init --recursive

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: BedrockReplay
          path: target/BedrockReplay-1.0.0-SNAPSHOT.jar
